const std = @import("std");
const rl = @import("raylib");

pub const Modifier = packed struct(u8) {
    left_control : bool,
    left_shift : bool,
    left_alt : bool,
    left_super : bool,
    right_control : bool,
    right_shift : bool,
    right_alt : bool,
    right_super : bool,

    pub fn as_u8(self: Modifier) u8 {
        return @bitCast(self);
    }
};

pub fn get(key: rl.KeyboardKey) ?u8 {
    return switch(key) {
        .a => 4,
        .b => 5,
        .c => 6,
        .d => 7,
        .e => 8,
        .f => 9,
        .g => 10,
        .h => 11,
        .i => 12,
        .j => 13,
        .k => 14,
        .l => 15,
        .m => 16,
        .n => 17,
        .o => 18,
        .p => 19,
        .q => 20,
        .r => 21,
        .s => 22,
        .t => 23,
        .u => 24,
        .v => 25,
        .w => 26,
        .x => 27,
        .y => 28,
        .z => 29,

        .one => 30,
        .two => 31,
        .three => 32,
        .four => 33,
        .five => 34,
        .six => 35,
        .seven => 36,
        .eight => 37,
        .nine => 38,
        .zero => 39,

        .enter => 40,
        .escape => 41,
        .backspace => 42,
        .tab => 43,
        .space => 44,
        .minus => 45,
        .equal => 46,
        .left_bracket => 47,
        .right_bracket => 48,
        .backslash => 49,

        .semicolon => 51,
        .comma => 54,
        .period => 55,
        .slash => 56,
        .caps_lock => 57,

        .f1 => 58,
        .f2 => 59,
        .f3 => 60,
        .f4 => 61,
        .f5 => 62,
        .f6 => 63,
        .f7 => 64,
        .f8 => 65,
        .f9 => 66,
        .f10 => 67,
        .f11 => 68,
        .f12 => 69,

        .print_screen => 70,
        .scroll_lock => 71,
        .pause => 72,
        .insert => 73,
        .home => 74,
        .page_up => 75,
        .delete => 76,
        .end => 77,
        .page_down => 78,
        .right => 79,
        .left => 80,
        .down => 81,
        .up => 82,

        .num_lock => 83,
        .kp_divide => 84,
        .kp_multiply => 85,
        .kp_subtract => 86,
        .kp_add => 87,
        .kp_enter => 88,
        .kp_1 => 89,
        .kp_2 => 90,
        .kp_3 => 91,
        .kp_4 => 92,
        .kp_5 => 93,
        .kp_6 => 94,
        .kp_7 => 95,
        .kp_8 => 96,
        .kp_9 => 97,
        .kp_0 => 98,
        .kp_decimal => 99,

        .kb_menu => 118,

        .left_super => 227,
        .right_super=> 231,

        else => null,
    };
}
